language: java
jdk: oraclejdk8
install: true
script:
  - mvn clean install
cache:
  directories:
  - $HOME/.m2
deploy:
  -
    on:
      branch: master
    provider: bintray
    skip_cleanup: true
    file: target/bin/bintray.json
    user: theyellow
    key: $BINTRAY_API_KEY
