language: java
jdk: oraclejdk8
install: true
script:
  - export DATE_TIME=`date +'%y.%m.%d %H:%M:%S'`
  - mvn clean install
cache:
  directories:
  - $HOME/.m2
deploy:
  -
    on:
      branch: master
    provider: bintray
    skip_cleanup: true
    file: bintray-descriptor.json
    user: theyellow
    key: $BINTRAY_API_KEY
    dry_run: false
